language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - "pip install -e . --upgrade"
  - "pipenv install --dev"

# command to run the dependencies
script:
  - "pipenv run pytest"
